#include "seatalk.h"

volatile unsigned char messages[NUMBER_OF_MESSAGES][MAX_MESSAGE_SIZE+1];
char string_buffer1[80];
char string_buffer2[80];
float depth;
float temperature;
float boatspeed;
float trip;
float boat_log;
signed int latitude_degrees;
signed int longitude_degrees;
float latitude_minutes;
float longitude_minutes;
signed char variation=0;
float tws; 
float twa;
float sog;
float awa=0.0;
unsigned int cog;
float aws=0.0;
unsigned int heading;
unsigned char hour;
unsigned char minute;
unsigned char second;
unsigned char year;
unsigned char month;
unsigned char date;
signed char rudder;
float distance_to_destination;
unsigned int bearing_to_destination;
message_handler handler;
volatile unsigned long second_tick_count=0L;
volatile unsigned long tenth_second_tick_count=0L;
unsigned long depth_receive_time=0L;
unsigned long awa_receive_time=0L;
unsigned long aws_receive_time=0L;
unsigned long heading_receive_time=0L;
unsigned long boatspeed_receive_time=0L;
unsigned long variation_receive_time=0L;
unsigned long sog_receive_time=0L;
unsigned long cog_receive_time=0L;
unsigned long latitude_receive_time=0L;
unsigned long longitude_receive_time=0L;
unsigned long temperature_receive_time=0L;
unsigned long triplog_receive_time=0L;
unsigned long nav_to_waypoint_receive_time=0L;
unsigned long true_wind_receive_time=0L;
unsigned long rudder_receive_time=0L;
unsigned long trip_receive_time=0L;
unsigned long log_receive_time=0L;
