#include "seatalk.h"

unsigned int flags;
volatile unsigned char messages[NUMBER_OF_MESSAGES][MAX_MESSAGE_SIZE+1];
char string_buffer1[150];
char direction_to_steer;
unsigned char keystroke;
float depth;
float temperature;
float boatspeed;
float trip;
float boat_log;
signed int latitude_degrees;
unsigned char lamps;
signed int longitude_degrees;
float latitude_minutes;
float longitude_minutes;
signed char variation=0;
float tws; 
float twa;
float sog;
float awa=0.0;
unsigned int cog;
float aws=0.0;
unsigned int heading;
unsigned char hour;
unsigned char minute;
unsigned char second;
unsigned char year;
unsigned char month;
unsigned char date;
unsigned char autopilot_state=APS_UNKNOWN;
float distance_to_destination;
unsigned int bearing_to_destination;
unsigned char arrival_circle_entered;
unsigned char perpendicular_passed;
char waypoint_id[4];
message_handler handler;
volatile unsigned long tenth_second_tick_count=0L;
volatile unsigned long second_tick_count=0L;
float xte;
