#include "anchor_watcher_2.h"
#include "seatalk.h"

float latitude_dfd;
float longitude_dfd;
float distance_m;
float latitude_dfd_ref;
float longitude_dfd_ref;
unsigned int heading_ref;
unsigned char wind_alarm_count;
unsigned char depth_alarm_count;
unsigned char sog_alarm_count;
unsigned char distance_alarm_count;
unsigned char heading_alarm_count;
setup_state_t setup_state;
unsigned char main_menu_position;
unsigned long earliest_next_alarm_time=0UL;
t_alarm alarm_type=alarm_none;
unsigned char backlight=3;
char number_buffer[8];
app_state_t app_state=WAITING_FOR_DATA;
volatile unsigned long one_second_tick_count=100UL;
volatile unsigned char tick=FALSE;
volatile unsigned char buttons=0;
volatile unsigned int c=0; 
char text_line[17];
volatile unsigned char seatalk_messages[SEATALK_NUMBER_OF_MESSAGES][SEATALK_MAX_MESSAGE_SIZE+1];
message_handler handler;
float depth;
int latitude_degrees;
signed int longitude_degrees;
float latitude_minutes;
float longitude_minutes;
float sog;
float awa;
float aws;
unsigned long depth_received_time=0UL;
unsigned long lat_received_time=0UL;
unsigned long long_received_time=0UL;
unsigned long sog_received_time=0UL;
unsigned long aws_received_time=0UL;
unsigned long heading_received_time=0UL;
unsigned long awa_received_time=0UL;
unsigned int heading;
int heading_difference;
unsigned char max_distance=50U;
unsigned int min_depth=20U;
unsigned char max_wind=20U;
unsigned char max_sog=20U;
unsigned char max_heading=45U;
unsigned char distance_enabled=TRUE;
unsigned char depth_enabled=TRUE;
unsigned char wind_enabled=TRUE;
unsigned char sog_enabled=TRUE;
unsigned char heading_enabled=TRUE;
unsigned char rearm_time=5U;
